#!/bin/sh

set -e

case "$(dpkg --print-architecture)" in
	amd64)
		_SOURCE="true"
		;;

	i386)
		_SOURCE="false"
		;;
esac

lb config noauto \
	--archive-areas "main contrib non-free non-free-firmware" \
	--backports true \
	--clean \
	--bootappend-live 'boot=live components splash noeject' \
	--debian-installer netboot \
	--debian-installer-gui true \
	--distribution bookworm \
	--ignore-system-defaults \
	--linux-packages "linux-image-6.10.6+bpo linux-headers-6.10.6+bpo" \
	--linux-flavours "amd64" \
	--memtest memtest86+ \
	--mode debian \
	--utc-time true \
	--source false \
"${@}"
